In [48]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re

In [4]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\user\onedrive - sri lanka institute of information technology\desktop\research\pharmalink\env\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\user\onedrive - sri lanka institute of information technology\desktop\research\pharmalink\env\lib\site-packages (from openpyxl) (2.0.0)

In [5]:
drug = pd.read_excel('../artifacts/MID.xlsx')

In [7]:
drug.head()

,Name,Link,Contains,ProductIntroduction,ProductUses,ProductBenefits,SideEffect,HowToUse,HowWorks,QuickTips,SafetyAdvice,Chemical_Class,Habit_Forming,Therapeutic_Class,Action_Class
0,Andol 0.5mg Tablet,https://www.1mg.com/drugs/andol-0.5mg-tablet-6...,Haloperidol (0.5mg),Andol 0.5mg Tablet can also be used for treati...,"\n \n \nul \""\""\n\n \n 0\n\n \n Schiz...",\n \n Schizophrenia \n \n Schizophrenia is ...,Most side effects do not require any medical a...,Take this medicine in the dose and duration as...,Andol 0.5mg Tablet is a typical antipsychotic....,\n \n Andol 0.5mg Tablet helps treat schizop...,"\nAlcohol\n,\nAndol 0.5mg Tablet may cause exc...",Butyrophenone Derivative,No,NEURO CNS,Typical Antipsychotic
1,Avastin 100mg Injection,https://www.1mg.com/drugs/avastin-100mg-inject...,Bevacizumab (100mg),"\np dir=\""ltr\"" style=\""line-height: 1.38; mar...","\n \n \nul \""\""\n\n \n 0\n\n \n Cance...",\n \n Cancer of colon and rectum \n \n Canc...,Most side effects do not require any medical a...,Your doctor or nurse will give you this medici...,Avastin 100mg Injection is a anti-angiogenic m...,\n \n Avastin 100mg Injection is an effectiv...,"\nAlcohol\n,\nIt is not known whether it is sa...",Monoclonal antibody (mAb),No,ANTI NEOPLASTICS,Vascular endothelial growth factor (VEGF) in...
2,Actorise 40 Injection,https://www.1mg.com/drugs/actorise-40-injectio...,Darbepoetin alfa (40mcg),Actorise 40 Injection is a medicine that needs...,"\n \n \nul \""\""\n\n \n 0\n\n \n Treat...",\n \n Treatment of Anemia due to chronic kid...,Most side effects do not require any medical a...,Your doctor or nurse will give you this medici...,Actorise 40 Injection is an erythropoiesis-sti...,\n \n Actorise 40 Injection helps in the tre...,"\nAlcohol\n,\nIt is not known whether it is sa...","Amino Acids, Peptides Analogues",No,BLOOD RELATED,Erythropoiesis-stimulating agent (ESA
3,Actorise 25 Injection,https://www.1mg.com/drugs/actorise-25-injectio...,Darbepoetin alfa (25mcg),Actorise 25 Injection is a medicine that needs...,"\n \n \nul \""\""\n\n \n 0\n\n \n Treat...",\n \n Treatment of Anemia due to chronic kid...,Most side effects do not require any medical a...,Your doctor or nurse will give you this medici...,Actorise 25 Injection is an erythropoiesis-sti...,\n \n Actorise 25 Injection helps in the tre...,"\nAlcohol\n,\nIt is not known whether it is sa...","Amino Acids, Peptides Analogues",No,BLOOD RELATED,Erythropoiesis-stimulating agent (ESA
4,Actorise 60 Injection,https://www.1mg.com/drugs/actorise-60-injectio...,Darbepoetin alfa (60mcg),Actorise 60 Injection is a medicine that needs...,"\n \n \nul \""\""\n\n \n 0\n\n \n Treat...",\n \n Treatment of Anemia due to chronic kid...,Most side effects do not require any medical a...,Your doctor or nurse will give you this medici...,Actorise 60 Injection is an erythropoiesis-sti...,\n \n Actorise 60 Injection helps in the tre...,"\nAlcohol\n,\nIt is not known whether it is sa...","Amino Acids, Peptides Analogues",No,BLOOD RELATED,Erythropoiesis-stimulating agent (ESA

In [9]:
# 2. Make a working copy (we'll edit this one)
df = drug.copy()

In [10]:
# 3. Function to clean text
def clean_text(x):
    if pd.isna(x):
        return ""
    x = str(x)
    x = re.sub(r'\s+', ' ', x)      # remove \n, \t, extra spaces
    x = re.sub(r'<.*?>', '', x)     # remove HTML tags
    x = x.strip()
    return x

In [11]:
# 4. Clean all object (text) columns in the copy
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = df[col].apply(clean_text)

In [12]:
# 5. (Optional) select useful columns into another df
useful_cols = [
    'Name',
    'Contains',
    'ProductIntroduction',
    'ProductUses',
    'ProductBenefits',
    'SideEffect',
    'HowToUse',
    'HowWorks',
    'QuickTips',
    'SafetyAdvice',
    'Chemical_Class',
    'Habit_Forming',
    'Therapeutic_Class',
    'Action_Class'
]

In [13]:
drug_clean = df[useful_cols].copy()

In [14]:
drug_clean.head()

,Name,Contains,ProductIntroduction,ProductUses,ProductBenefits,SideEffect,HowToUse,HowWorks,QuickTips,SafetyAdvice,Chemical_Class,Habit_Forming,Therapeutic_Class,Action_Class
0,Andol 0.5mg Tablet,Haloperidol (0.5mg),Andol 0.5mg Tablet can also be used for treati...,"\n \n ul \""\"" \n 0 \n Schizophrenia\n \n \n",Schizophrenia Schizophrenia is a mental disord...,Most side effects do not require any medical a...,Take this medicine in the dose and duration as...,Andol 0.5mg Tablet is a typical antipsychotic....,Andol 0.5mg Tablet helps treat schizophrenia. ...,"Alcohol , Andol 0.5mg Tablet may cause excessi...",Butyrophenone Derivative,No,NEURO CNS,Typical Antipsychotic
1,Avastin 100mg Injection,Bevacizumab (100mg),"p dir=\""ltr\"" style=\""line-height: 1.38; margi...","\n \n ul \""\"" \n 0 \n Cancer of colon and rect...",Cancer of colon and rectum Cancer of the colon...,Most side effects do not require any medical a...,Your doctor or nurse will give you this medici...,Avastin 100mg Injection is a anti-angiogenic m...,"Avastin 100mg Injection is an effective, first...","Alcohol , It is not known whether it is safe t...",Monoclonal antibody (mAb),No,ANTI NEOPLASTICS,Vascular endothelial growth factor (VEGF) inhi...
2,Actorise 40 Injection,Darbepoetin alfa (40mcg),Actorise 40 Injection is a medicine that needs...,"\n \n ul \""\"" \n 0 \n Treatment of Anemia due ...",Treatment of Anemia due to chronic kidney dise...,Most side effects do not require any medical a...,Your doctor or nurse will give you this medici...,Actorise 40 Injection is an erythropoiesis-sti...,Actorise 40 Injection helps in the treatment o...,"Alcohol , It is not known whether it is safe t...","Amino Acids, Peptides Analogues",No,BLOOD RELATED,Erythropoiesis-stimulating agent (ESA
3,Actorise 25 Injection,Darbepoetin alfa (25mcg),Actorise 25 Injection is a medicine that needs...,"\n \n ul \""\"" \n 0 \n Treatment of Anemia due ...",Treatment of Anemia due to chronic kidney dise...,Most side effects do not require any medical a...,Your doctor or nurse will give you this medici...,Actorise 25 Injection is an erythropoiesis-sti...,Actorise 25 Injection helps in the treatment o...,"Alcohol , It is not known whether it is safe t...","Amino Acids, Peptides Analogues",No,BLOOD RELATED,Erythropoiesis-stimulating agent (ESA
4,Actorise 60 Injection,Darbepoetin alfa (60mcg),Actorise 60 Injection is a medicine that needs...,"\n \n ul \""\"" \n 0 \n Treatment of Anemia due ...",Treatment of Anemia due to chronic kidney dise...,Most side effects do not require any medical a...,Your doctor or nurse will give you this medici...,Actorise 60 Injection is an erythropoiesis-sti...,Actorise 60 Injection helps in the treatment o...,"Alcohol , It is not known whether it is safe t...","Amino Acids, Peptides Analogues",No,BLOOD RELATED,Erythropoiesis-stimulating agent (ESA

In [15]:
# Combine all relevant text columns into a single NLP feature
text_cols = [
    'ProductIntroduction',
    'ProductUses',
    'ProductBenefits',
    'SideEffect',
    'HowToUse',
    'HowWorks',
    'QuickTips',
    'SafetyAdvice'
]

drug_clean['combined_text'] = drug_clean[text_cols].fillna('').agg(' '.join, axis=1)

drug_clean[['Name', 'Contains', 'combined_text']].head()

,Name,Contains,combined_text
0,Andol 0.5mg Tablet,Haloperidol (0.5mg),Andol 0.5mg Tablet can also be used for treati...
1,Avastin 100mg Injection,Bevacizumab (100mg),"p dir=\""ltr\"" style=\""line-height: 1.38; margi..."
2,Actorise 40 Injection,Darbepoetin alfa (40mcg),Actorise 40 Injection is a medicine that needs...
3,Actorise 25 Injection,Darbepoetin alfa (25mcg),Actorise 25 Injection is a medicine that needs...
4,Actorise 60 Injection,Darbepoetin alfa (60mcg),Actorise 60 Injection is a medicine that needs...

In [16]:
def clean_html(x):
    if pd.isna(x):
        return ""
    x = str(x)

    # Remove real html tags <...>
    x = re.sub(r"<.*?>", " ", x)

    # Remove pseudo-html tags like: p dir="ltr", style="...", span ...
    x = re.sub(r'\b(?:p|span|div|dir|style|class|align)\b[^>]*', ' ', x, flags=re.IGNORECASE)

    # Remove leftover escaped quotes \" \'
    x = x.replace('\\"', ' ').replace("\\'", ' ')

    # Remove any multiple spaces/newlines
    x = re.sub(r"\s+", " ", x)

    return x.strip()

In [17]:
drug_clean['combined_text'] = drug_clean['combined_text'].apply(clean_html)
drug_clean[['Name', 'combined_text']].head()

                      Name                                      combined_text
0       Andol 0.5mg Tablet  Andol 0.5mg Tablet can also be used for treati...
1  Avastin 100mg Injection
2    Actorise 40 Injection  Actorise 40 Injection is a medicine that needs...
3    Actorise 25 Injection  Actorise 25 Injection is a medicine that needs...
4    Actorise 60 Injection  Actorise 60 Injection is a medicine that needs...

In [18]:
from sklearn.preprocessing import LabelEncoder

cat_cols = ['Chemical_Class', 'Habit_Forming', 'Therapeutic_Class', 'Action_Class']

encoders = {}
for col in cat_cols:
    le = LabelEncoder()
    drug_clean[col] = le.fit_transform(drug_clean[col].astype(str))
    encoders[col] = le

drug_clean[cat_cols].head()

   Chemical_Class  Habit_Forming  Therapeutic_Class  Action_Class
0             203              1                 21           387
1             470              1                  7           396
2              65              1                  9           163
3              65              1                  9           163
4              65              1                  9           163

In [19]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\user\onedrive - sri lanka institute of information technology\desktop\research\pharmalink\env\lib\site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in c:\users\user\onedrive - sri lanka institute of information technology\desktop\research\pharmalink\env\lib\site-packages (from scikit-learn) (2.3.5)
Requirement already satisfied: scipy>=1.8.0 in c:\users\user\onedrive - sri lanka institute of information technology\desktop\research\pharmalink\env\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\user\onedrive - sri lanka institute of information technology\desktop\research\pharmalink\env\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\user\onedrive - sri lanka institute of information technology\desktop\research\pharmalink\env\lib\site-packages (from scikit-learn) (3.6.0)

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    stop_words='english',
    max_features=5000
)

X_text = tfidf.fit_transform(drug_clean['combined_text'])
X_text

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 30598820 stored elements and shape (192807, 5000)>

In [21]:
import scipy.sparse as sp

X_cat = drug_clean[cat_cols].values

# Combine sparse TF-IDF with dense categorical features
X = sp.hstack([X_text, X_cat])

X

<COOrdinate sparse matrix of dtype 'float64'
	with 31163126 stored elements and shape (192807, 5004)>

In [22]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=15, random_state=42)
clusters = kmeans.fit_predict(X)

drug_clean['cluster'] = clusters
drug_clean[['Name', 'Contains', 'cluster']].head(20)

,Name,Contains,cluster
0,Andol 0.5mg Tablet,Haloperidol (0.5mg),6
1,Avastin 100mg Injection,Bevacizumab (100mg),7
2,Actorise 40 Injection,Darbepoetin alfa (40mcg),14
3,Actorise 25 Injection,Darbepoetin alfa (25mcg),14
4,Actorise 60 Injection,Darbepoetin alfa (60mcg),14
5,Azel 80 Capsule,Enzalutamide (80mg),13
6,Avastin 400mg Injection,Bevacizumab (400mg),7
7,Azel 40mg Capsule,Enzalutamide (40mg),13
8,Actorise 200 Injection,Darbepoetin alfa (200mcg),14
9,Actorise 100 Injection,Darbepoetin alfa (100mcg),14
10,Azacytin Injection,Azacitidine (100mg),4
11,Alecensa 150mg Capsule,Alectinib (150mg),6
12,Aromasin 25mg Tablet,Exemestane (25mg),8
13,Augmentin 625 Duo Tablet,Amoxycillin (500mg)+ Clavulanic Acid (125mg),1
14,Ascoril LS Syrup,Ambroxol (30mg/5ml)+ Levosalbutamol (1mg/5ml)+...,1
15,Azithral 500 Tablet,Azithromycin (500mg),11
16,Amoxyclav 625 Tablet,Amoxycillin (500mg)+ Clavulanic Acid (125mg),1
17,Allegra 120mg Tablet,Fexofenadine (120mg),3
18,Aricep 5 Tablet,Donepezil (5mg),10
19,Avil 25 Tablet,Pheniramine (25mg),9

In [23]:
# Work with lowercase text for easier matching
safety_text = (
    drug_clean['SafetyAdvice'].fillna('') + ' ' +
    drug_clean['combined_text'].fillna('')
).str.lower()

In [24]:
def get_risk_label(text: str) -> int:
    risk = 0  # default = no clear food/alcohol interaction

    # ---------- HIGH RISK PATTERNS (label 2) ----------
    high_risk_words = [
        'do not take with alcohol',
        'do not drink alcohol',
        'avoid alcohol completely',
        'avoid alcohol',
        'serious liver damage',
        'severe liver damage',
        'stomach bleeding',
        'serious bleeding',
        'life-threatening',
        'grapefruit juice',
        'do not take with food',
        'on an empty stomach only',
        'contraindicated with alcohol',
        'fatal',
    ]

    if any(kw in text for kw in high_risk_words):
        risk = 2

    # ---------- MODERATE RISK PATTERNS (label 1) ----------
    moderate_words = [
        'take with food',
        'take it with food',
        'take this medicine with food',
        'may cause stomach upset',
        'to reduce stomach upset',
        'limit alcohol',
        'avoid drinking too much alcohol',
        'may cause dizziness',
        'may cause drowsiness',
        'use caution while driving',
        'avoid grapefruit',
        'take after food',
        'take before food',
    ]

    if any(kw in text for kw in moderate_words):
        # upgrade risk only if not already 2
        risk = max(risk, 1)

    return risk

drug_clean['risk_label'] = safety_text.apply(get_risk_label)

drug_clean[['Name', 'Contains', 'risk_label']].head(20)

,Name,Contains,risk_label
0,Andol 0.5mg Tablet,Haloperidol (0.5mg),1
1,Avastin 100mg Injection,Bevacizumab (100mg),0
2,Actorise 40 Injection,Darbepoetin alfa (40mcg),0
3,Actorise 25 Injection,Darbepoetin alfa (25mcg),0
4,Actorise 60 Injection,Darbepoetin alfa (60mcg),0
5,Azel 80 Capsule,Enzalutamide (80mg),2
6,Avastin 400mg Injection,Bevacizumab (400mg),0
7,Azel 40mg Capsule,Enzalutamide (40mg),2
8,Actorise 200 Injection,Darbepoetin alfa (200mcg),0
9,Actorise 100 Injection,Darbepoetin alfa (100mcg),0
10,Azacytin Injection,Azacitidine (100mg),2
11,Alecensa 150mg Capsule,Alectinib (150mg),1
12,Aromasin 25mg Tablet,Exemestane (25mg),1
13,Augmentin 625 Duo Tablet,Amoxycillin (500mg)+ Clavulanic Acid (125mg),0
14,Ascoril LS Syrup,Ambroxol (30mg/5ml)+ Levosalbutamol (1mg/5ml)+...,1
15,Azithral 500 Tablet,Azithromycin (500mg),0
16,Amoxyclav 625 Tablet,Amoxycillin (500mg)+ Clavulanic Acid (125mg),0
17,Allegra 120mg Tablet,Fexofenadine (120mg),0
18,Aricep 5 Tablet,Donepezil (5mg),2
19,Avil 25 Tablet,Pheniramine (25mg),2

In [25]:
drug_clean['risk_label'].value_counts()

risk_label
0    105685
1     51921
2     35201
Name: count, dtype: int64

In [26]:
import scipy.sparse as sp

cat_cols = ['Chemical_Class', 'Habit_Forming', 'Therapeutic_Class', 'Action_Class']

X_cat = drug_clean[cat_cols].values
X = sp.hstack([X_text, X_cat])  # final features

y = drug_clean['risk_label'].values
X.shape, y.shape

((192807, 5004), (192807,))

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [28]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=None,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, n_jobs=-1, random_state=42)

In [29]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred = rf.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00     21137
           1       1.00      0.99      1.00     10385
           2       1.00      0.98      0.99      7040

    accuracy                           1.00     38562
   macro avg       1.00      0.99      0.99     38562
weighted avg       1.00      1.00      1.00     38562

[[21124     8     5]
 [   51 10331     3]
 [  107     5  6928]]

In [31]:
drug_clean[['Name', 'risk_label']].head()

                      Name  risk_label
0       Andol 0.5mg Tablet           1
1  Avastin 100mg Injection           0
2    Actorise 40 Injection           0
3    Actorise 25 Injection           0
4    Actorise 60 Injection           0

In [32]:
X = X.tocsr()

In [33]:
rf.predict(X[:5])

array([1, 0, 0, 0, 0])

In [34]:
from sklearn.model_selection import train_test_split

# X and y already created earlier
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

rf.fit(X_train, y_train)   # make sure model is trained on train set

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_pred = rf.predict(X_test)

In [35]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification report:\n")
print(classification_report(y_test, y_pred))

print("\nConfusion matrix:\n")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9953581245786007

Classification report:

              precision    recall  f1-score   support

           0       0.99      1.00      1.00     21137
           1       1.00      0.99      1.00     10385
           2       1.00      0.98      0.99      7040

    accuracy                           1.00     38562
   macro avg       1.00      0.99      0.99     38562
weighted avg       1.00      1.00      1.00     38562


Confusion matrix:

[[21124     8     5]
 [   51 10331     3]
 [  107     5  6928]]

In [36]:
drug_clean['risk_label'].value_counts()

risk_label
0    105685
1     51921
2     35201
Name: count, dtype: int64

In [37]:
import joblib

joblib.dump(rf, "../model/food_drug_risk_model.pkl")
joblib.dump(tfidf, "../model/tfidf_vectorizer.pkl")
joblib.dump(encoders, "../model/category_encoders.pkl")

['../model/category_encoders.pkl']

In [38]:
import joblib
import scipy.sparse as sp
import numpy as np

# Load saved files
rf_loaded = joblib.load("../model/food_drug_risk_model.pkl")
tfidf_loaded = joblib.load("../model/tfidf_vectorizer.pkl")
encoders_loaded = joblib.load("../model/category_encoders.pkl")

print("Model, vectorizer, and encoders loaded successfully!")

Model, vectorizer, and encoders loaded successfully!

In [41]:
cat_cols = ['Chemical_Class', 'Habit_Forming', 
            'Therapeutic_Class', 'Action_Class']

def predict_drug_risk(index):
    # 1. extract text
    text = drug_clean.loc[index, 'combined_text']
    
    # 2. vectorize text (sparse matrix)
    text_vec = tfidf_loaded.transform([text])   # shape (1, n_features)
    
    # 3. get categorical features and ensure numeric dtype
    cat_vals = drug_clean.loc[index, cat_cols].astype(float).values.reshape(1, -1)
    
    # 4. convert categorical to sparse matrix
    cat_sparse = sp.csr_matrix(cat_vals)
    
    # 5. combine text + categorical into one sparse row
    X_input = sp.hstack([text_vec, cat_sparse]).tocsr()
    
    # 6. predict risk label
    pred = rf_loaded.predict(X_input)[0]
    return pred

In [42]:
for i in range(5):
    print(drug_clean.loc[i, "Name"], "→ predicted risk:", predict_drug_risk(i),
          "| true label:", drug_clean.loc[i, "risk_label"])

Andol 0.5mg Tablet → predicted risk: 1 | true label: 1
Avastin 100mg Injection → predicted risk: 0 | true label: 0
Actorise 40 Injection → predicted risk: 0 | true label: 0
Actorise 25 Injection → predicted risk: 0 | true label: 0
Actorise 60 Injection → predicted risk: 0 | true label: 0

In [43]:
risk_map = {
    0: "Safe — No major food or alcohol interaction identified.",
    1: "Moderate — Use with caution. Follow food/alcohol advice carefully.",
    2: "High Risk — Avoid certain foods/alcohol. Consult a doctor or pharmacist."
}

def explain_drug_risk(index):
    pred = predict_drug_risk(index)
    msg = risk_map[pred]
    return pred, msg

In [44]:
for i in range(5):
    name = drug_clean.loc[i, "Name"]
    pred, msg = explain_drug_risk(i)
    print(f"{name} → predicted label: {pred} | {msg}")

Andol 0.5mg Tablet → predicted label: 1 | Moderate — Use with caution. Follow food/alcohol advice carefully.
Avastin 100mg Injection → predicted label: 0 | Safe — No major food or alcohol interaction identified.
Actorise 40 Injection → predicted label: 0 | Safe — No major food or alcohol interaction identified.
Actorise 25 Injection → predicted label: 0 | Safe — No major food or alcohol interaction identified.
Actorise 60 Injection → predicted label: 0 | Safe — No major food or alcohol interaction identified.

In [45]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification report:\n")
print(classification_report(y_test, y_pred))

print("\nConfusion matrix:\n")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9953581245786007

Classification report:

              precision    recall  f1-score   support

           0       0.99      1.00      1.00     21137
           1       1.00      0.99      1.00     10385
           2       1.00      0.98      0.99      7040

    accuracy                           1.00     38562
   macro avg       1.00      0.99      0.99     38562
weighted avg       1.00      1.00      1.00     38562


Confusion matrix:

[[21124     8     5]
 [   51 10331     3]
 [  107     5  6928]]

In [53]:
import os

for root, dirs, files in os.walk('../', topdown=True):
    for name in files:
        if "Sri" in name or "Food" in name or "Composition" in name:
            print(os.path.join(root, name))

../artifacts\Sri Lanka Food Composition Table .csv
../frontend\src\pages\FoodDrugInteraction.jsx

In [55]:
food = pd.read_csv('../artifacts/Sri Lanka Food Composition Table .csv')

In [57]:
food.head()

,FCT source,drfoodlistcode,drfoodlistdesc,Recipe/Single food item,Energy (kcal),Protein (g),Total fats (g),Total carbohydrates (g),Fiber (g),Starch (g),...,Phosphorus (mg),Potassium (mg),Sodium (mg),Selenium (mcg),Retinol (mcg),Saturated fatty acids (g),Mono-unsaturated fatty acids (g),Poly-unsaturated fatty acids (g),Free sugars (g),Unnamed: 36
0,"ASEAN FCT #AAP1 Beer, pale pilsen",10010001.0,BEER,S,43.0,0.0,0.46,3.55,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Wayamba 2022 SPIRITS,10010002.0,"LIQUOR, ARAK",S,222.0,0.0,0.00,0.00,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Wayamba 2022 SPIRITS,10010003.0,"LIQUOR, KASIPPU",S,222.0,0.0,0.00,0.00,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Wayamba 2022 SPIRITS,10010004.0,"LIQUOR, TODDY, COCONUT",S,222.0,0.0,0.00,0.00,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Wayamba 2022 SPIRITS,10010006.0,"LIQUOR, TODDY, KITUL",S,222.0,0.0,0.00,0.00,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
food.columns

Index(['FCT source', 'drfoodlistcode', 'drfoodlistdesc',
       'Recipe/Single food item', 'Energy (kcal)', 'Protein (g)',
       'Total fats (g)', 'Total carbohydrates (g)', 'Fiber (g)', 'Starch (g)',
       'Cholesterol (mg)', 'Calcium (mg)', 'Magnesium (mg)', 'Iron (mg)',
       'Zinc (mg)', 'Thiamin (mg)', 'Riboflavin (mg)', 'Niacin (mg)',
       'Vitamin B6 (mg)', 'Vitamin B12 (mcg)', 'Folate, ug', 'Vitamin C (mg)',
       'Retinol Activity Equivalents (ug)', 'Vitamin E (ug)',
       'total n-6 fas (% of energy)', 'total n-3 fas (% of energy)',
       'Vitamin B5 (mg)', 'Phosphorus (mg)', 'Potassium (mg)', 'Sodium (mg)',
       'Selenium (mcg)', 'Retinol (mcg)', 'Saturated fatty acids (g)',
       'Mono-unsaturated fatty acids (g)', 'Poly-unsaturated fatty acids (g)',
       'Free sugars (g)', 'Unnamed: 36'],
      dtype='object')

In [59]:
# Rename important columns for ease
food = food.rename(columns={
    'drfoodlistdesc': 'Food',
    'Energy (kcal)': 'energy',
    'Protein (g)': 'protein',
    'Total fats (g)': 'fat',
    'Total carbohydrates (g)': 'carbs',
    'Fiber (g)': 'fiber',
    'Calcium (mg)': 'calcium',
    'Iron (mg)': 'iron',
    'Vitamin C (mg)': 'vitamin_c',
    'Folate, ug': 'folate',
    'Retinol Activity Equivalents (ug)': 'vitamin_a',
    'Vitamin E (ug)': 'vitamin_e'
})

# Drop useless columns
food = food.drop(columns=['Unnamed: 36'])

# Replace NaN with 0 for nutrient values
food = food.fillna(0)

food.head()

,FCT source,drfoodlistcode,Food,Recipe/Single food item,energy,protein,fat,carbs,fiber,Starch (g),...,Vitamin B5 (mg),Phosphorus (mg),Potassium (mg),Sodium (mg),Selenium (mcg),Retinol (mcg),Saturated fatty acids (g),Mono-unsaturated fatty acids (g),Poly-unsaturated fatty acids (g),Free sugars (g)
0,"ASEAN FCT #AAP1 Beer, pale pilsen",10010001.0,BEER,S,43.0,0.0,0.46,3.55,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Wayamba 2022 SPIRITS,10010002.0,"LIQUOR, ARAK",S,222.0,0.0,0.00,0.00,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Wayamba 2022 SPIRITS,10010003.0,"LIQUOR, KASIPPU",S,222.0,0.0,0.00,0.00,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Wayamba 2022 SPIRITS,10010004.0,"LIQUOR, TODDY, COCONUT",S,222.0,0.0,0.00,0.00,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Wayamba 2022 SPIRITS,10010006.0,"LIQUOR, TODDY, KITUL",S,222.0,0.0,0.00,0.00,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [75]:
# define nutrient columns again (to avoid NameError)
nutrient_cols = [
    'energy', 'protein', 'fat', 'carbs', 'fiber',
    'calcium', 'iron', 'vitamin_c', 'folate', 'vitamin_a', 'vitamin_e',
    'vitamin_k_proxy'
]

for col in nutrient_cols:
    food_subset[col] = pd.to_numeric(food_subset[col], errors='coerce').fillna(0.0)

food_subset['is_alcohol'] = food_subset['is_alcohol'].astype(int)
food_subset['is_leafy_green'] = food_subset['is_leafy_green'].astype(int)


food_subset.head()

,Food,energy,protein,fat,carbs,fiber,calcium,iron,vitamin_c,folate,vitamin_a,vitamin_e,is_alcohol,is_leafy_green,vitamin_k_proxy
0,BEER,43.0,0.0,0.46,3.55,0.0,4.0,0.02,0.0,6.0,0.0,0.0,1,0,0
1,"LIQUOR, ARAK",222.0,0.0,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,1,0,0
2,"LIQUOR, KASIPPU",222.0,0.0,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,1,0,0
3,"LIQUOR, TODDY, COCONUT",222.0,0.0,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,1,0,0
4,"LIQUOR, TODDY, KITUL",222.0,0.0,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,1,0,0

In [76]:
# add alcohol flag (1 = alcohol, 0 = not alcohol)
alcohol_words = ['beer', 'liquor', 'toddy', 'arak', 'wine', 'spirits']

def is_alcohol(name: str) -> int:
    name = str(name).lower()
    return int(any(word in name for word in alcohol_words))

food_subset['is_alcohol'] = food_subset['Food'].apply(is_alcohol)

food_subset.head(10)

,Food,energy,protein,fat,carbs,fiber,calcium,iron,vitamin_c,folate,vitamin_a,vitamin_e,is_alcohol,is_leafy_green,vitamin_k_proxy
0,BEER,43.0,0.0,0.46,3.55,0.0,4.00,0.02,0.0,6.0,0.0,0.0,1,0,0
1,"LIQUOR, ARAK",222.0,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,1,0,0
2,"LIQUOR, KASIPPU",222.0,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,1,0,0
3,"LIQUOR, TODDY, COCONUT",222.0,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,1,0,0
4,"LIQUOR, TODDY, KITUL",222.0,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,1,0,0
5,"LIQUOR, TODDY, PALMYRA",222.0,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,1,0,0
6,"LIQUOR, HARD (>35% ABV), NON-SPECIFIC",222.0,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,1,0,0
7,"COCONUT WATER, BOTTLED, SWEETENED",31.4,0.0,0.28,7.43,0.0,7.14,0.00,0.0,0.0,0.0,0.0,0,0,0
8,"COCONUT WATER, FRESH, UNSWEETENED",14.0,0.3,0.20,3.20,0.0,27.00,0.06,0.6,10.9,0.0,0.5,0,0,0
9,FRUIT AND MILK DRINK,72.0,3.6,1.50,11.70,0.0,115.00,0.62,0.0,2.0,0.0,0.0,0,0,0

In [78]:
import re

def check_food_drug_interaction(drug_index, food_row):
    # --- drug info ---
    drug_name = drug_clean.loc[drug_index, 'Name']
    drug_contains = str(drug_clean.loc[drug_index, 'Contains']).lower()
    drug_text = str(drug_clean.loc[drug_index, 'combined_text']).lower()
    
    # vitamin K proxy from food
    vitk = float(food_row.get('vitamin_k_proxy', 0.0))

    # base risk from your ML drug model
    base_risk = predict_drug_risk(drug_index)
    risk = base_risk
    
    # --- food info ---
    calcium = float(food_row['calcium'])
    iron = float(food_row['iron'])
    fat = float(food_row['fat'])
    fiber = float(food_row['fiber'])
    is_alcohol = int(food_row.get('is_alcohol', 0))
    food_name = food_row['Food']
    
    # 1) Alcohol + CNS/sedative/antipsychotic drugs -> high risk
    cns_keywords = ['antipsychotic', 'antidepressant', 'antihistamine', 'sedative', 'antiepileptic']
    if is_alcohol == 1 and any(kw in drug_text for kw in cns_keywords):
        risk = max(risk, 2)
    
    # 2) Antibiotics + high calcium foods (milk, cheese etc.) -> moderate/high risk
    abx_keywords = ['amoxycillin', 'ciprofloxacin', 'tetracycline', 'doxycycline']
    if any(kw in drug_contains for kw in abx_keywords) and calcium > 200:
        risk = max(risk, 1)
    
    # 3) Thyroid medicines (levothyroxine) + high iron -> high risk
    if 'levothyroxine' in drug_contains and iron > 5:
        risk = max(risk, 2)
    
    # 4) Very high fat foods + drugs where fat affects absorption
    if fat > 20 and 'take on an empty stomach' in drug_text:
        risk = max(risk, 1)
    
    # 5) High fiber + slow absorption warning
    if fiber > 5 and 'slow absorption' in drug_text:
        risk = max(risk, 1)
    
    # 6) Warfarin / anticoagulant + high vitamin K leafy greens -> high risk
    if ('warfarin' in drug_contains or 'anticoagulant' in drug_text) and vitk > 100:
        risk = max(risk, 2)

    return int(risk)


# pick first 3 drugs and first 10 foods to test
for i in range(3):
    print("DRUG:", drug_clean.loc[i, "Name"])
    for _, row in food_subset.head(10).iterrows():
        r = check_food_drug_interaction(i, row)
        print("   Food:", row['Food'], "-> risk:", r)
    print("-" * 40)

DRUG: Andol 0.5mg Tablet
   Food: BEER -> risk: 2
   Food: LIQUOR, ARAK -> risk: 2
   Food: LIQUOR, KASIPPU -> risk: 2
   Food: LIQUOR, TODDY, COCONUT -> risk: 2
   Food: LIQUOR, TODDY, KITUL -> risk: 2
   Food: LIQUOR, TODDY, PALMYRA -> risk: 2
   Food: LIQUOR, HARD (>35% ABV), NON-SPECIFIC -> risk: 2
   Food: COCONUT WATER, BOTTLED, SWEETENED -> risk: 1
   Food: COCONUT WATER, FRESH, UNSWEETENED -> risk: 1
   Food: FRUIT AND MILK DRINK -> risk: 1
----------------------------------------
DRUG: Avastin 100mg Injection
   Food: BEER -> risk: 0
   Food: LIQUOR, ARAK -> risk: 0
   Food: LIQUOR, KASIPPU -> risk: 0
   Food: LIQUOR, TODDY, COCONUT -> risk: 0
   Food: LIQUOR, TODDY, KITUL -> risk: 0
   Food: LIQUOR, TODDY, PALMYRA -> risk: 0
   Food: LIQUOR, HARD (>35% ABV), NON-SPECIFIC -> risk: 0
   Food: COCONUT WATER, BOTTLED, SWEETENED -> risk: 0
   Food: COCONUT WATER, FRESH, UNSWEETENED -> risk: 0
   Food: FRUIT AND MILK DRINK -> risk: 0
----------------------------------------
DRUG: Actorise 40 Injection
   Food: BEER -> risk: 0
   Food: LIQUOR, ARAK -> risk: 0
   Food: LIQUOR, KASIPPU -> risk: 0
   Food: LIQUOR, TODDY, COCONUT -> risk: 0
   Food: LIQUOR, TODDY, KITUL -> risk: 0
   Food: LIQUOR, TODDY, PALMYRA -> risk: 0
   Food: LIQUOR, HARD (>35% ABV), NON-SPECIFIC -> risk: 0
   Food: COCONUT WATER, BOTTLED, SWEETENED -> risk: 0
   Food: COCONUT WATER, FRESH, UNSWEETENED -> risk: 0
   Food: FRUIT AND MILK DRINK -> risk: 0
----------------------------------------

In [94]:
risk_map = {
    0: "Safe – No major interaction identified.",
    1: "Moderate – Use with caution and follow advice.",
    2: "High Risk – Avoid this combination; consult a doctor or pharmacist."
}

cns_keywords = ['antipsychotic', 'antidepressant', 'antihistamine', 'sedative', 'antiepileptic']
abx_keywords = ['amoxycillin', 'ciprofloxacin', 'tetracycline', 'doxycycline']

def explain_food_drug_interaction(drug_index, food_name):
    # locate food row
    row = food_subset[food_subset['Food'] == food_name].iloc[0]
    
    # run existing risk logic
    risk = check_food_drug_interaction(drug_index, row)
    
    # gather reasons (for explanation text)
    reasons = []
    
    drug_text = str(drug_clean.loc[drug_index, 'combined_text']).lower()
    drug_contains = str(drug_clean.loc[drug_index, 'Contains']).lower()
    
    calcium = row['calcium']
    iron = row['iron']
    fat = row['fat']
    fiber = row['fiber']
    is_alcohol = row['is_alcohol']
    vitk = float(row.get('vitamin_k_proxy', 0.0))
    
    # alcohol + CNS
    if is_alcohol == 1 and any(kw in drug_text for kw in cns_keywords):
        reasons.append("Alcohol can increase drowsiness and CNS side effects of this medicine.")
    
    # antibiotics + calcium
    if any(kw in drug_contains for kw in abx_keywords) and calcium > 200:
        reasons.append("High calcium in this food can reduce absorption of this antibiotic.")
    
    # thyroid + iron
    if 'levothyroxine' in drug_contains and iron > 5:
        reasons.append("High iron can reduce the effectiveness of thyroid medication.")
    
    # high fat
    if fat > 20 and 'take on an empty stomach' in drug_text:
        reasons.append("High fat may slow down or change absorption of this medicine.")
    
    # high fibre
    if fiber > 5 and 'slow absorption' in drug_text:
        reasons.append("High fibre may reduce absorption of this medicine.")

    # 6) vitamin K proxy + warfarin / anticoagulant
    if ('warfarin' in drug_contains or 'anticoagulant' in drug_text) and vitk > 100:
        reasons.append("Leafy green foods rich in vitamin K can reduce the blood-thinning effect of anticoagulant medicines.")
    
    # build message
    base_msg = risk_map[risk]
    if reasons:
        explanation = base_msg + " " + " ".join(reasons)
    else:
        explanation = base_msg + " No specific nutrient-triggered interaction was detected."
    
    return risk, explanation

In [95]:
andol_idx = 0  # if Andol is row 0 as before
risk, msg = explain_food_drug_interaction(andol_idx, "BEER")
print("Andol 0.5mg Tablet + BEER ->", risk, "|", msg)

Andol 0.5mg Tablet + BEER -> 2 | High Risk – Avoid this combination; consult a doctor or pharmacist. Alcohol can increase drowsiness and CNS side effects of this medicine.

In [70]:
def recommend_safe_foods(drug_index, top_n=10):
    rows = []
    for _, row in food_subset.iterrows():
        r = check_food_drug_interaction(drug_index, row)
        if r == 0:
            rows.append(row)
    safe_df = pd.DataFrame(rows)
    
    # show only a few useful columns
    cols_show = ['Food', 'energy', 'protein', 'fat', 'carbs', 'fiber']
    return safe_df[cols_show].head(top_n)

In [71]:
leafy_words = [
    'spinach', 'mukunuwenna', 'gotu kola', 'kankun',
    'kale', 'cabbage', 'lettuce', 'amaranth', 'gotukola',
    'green leaves', 'leafy'
]

def is_leafy(name: str) -> int:
    name = str(name).lower()
    return int(any(w in name for w in leafy_words))

food_subset['is_leafy_green'] = food_subset['Food'].apply(is_leafy)

# simple proxy: give leafy greens a “high” vitamin_k value
food_subset['vitamin_k_proxy'] = food_subset['is_leafy_green'] * 300  # 300 µg as a dummy value

In [82]:
warfarin_rows = drug_clean[drug_clean['Contains'].str.contains('warfarin', case=False, na=False)]
warfarin_rows[['Name', 'Contains']].head()

                                  Name        Contains
69064   Genericart Warfarin 2mg Tablet  Warfarin (2mg)
173199            Uniwarfin 1mg Tablet  Warfarin (1mg)
185844                   Warf 5 Tablet  Warfarin (5mg)
185874                   Warf 5 Tablet  Warfarin (5mg)
185905                   Warf 2 Tablet  Warfarin (2mg)

In [83]:
warfarin_idx = 69064
drug_clean.loc[warfarin_idx, ['Name', 'Contains']]

Name        Genericart Warfarin 2mg Tablet
Contains                    Warfarin (2mg)
Name: 69064, dtype: object

In [84]:
leafy_foods = food_subset[food_subset['is_leafy_green'] == 1][['Food']].head(20)
leafy_foods

                                                  Food
24                       KENDA, LEAFY VEGETABLE & RICE
327   RED LENTILS AND SPINACH, BOILED, W/ COCONUT MILK
330   RED LENTILS AND CABBAGE, BOILED, W/ COCONUT MILK
345     LEGUMES AND LEAFY GREENS, NFS, W/ COCONUT MILK
549  TURKEY BERRY (THIBBATU) AND LEAFY GREENS, NFS,...
621  AMARANTH LEAVES, FRESH OR WATER-COOKED MALLUM ...
622  AMARANTH LEAVES, TEMPERED MALLUM W/ SCRAPED CO...
623                          AMARANTH LEAVES, TEMPERED
624                   SPINACH, BOILED, W/ COCONUT MILK
625           AMARANTH LEAVES, BOILED, W/ COCONUT MILK
626  SPINACH, FRESH OR WATER-COOKED MALLUM W/ SCRAP...
629  CABBAGE LEAVES, FRESH OR WATER-COOKED MALLUM W...
630  CABBAGE LEAVES, TEMPERED MALLUM W/ SCRAPED COC...
631                           CABBAGE LEAVES, TEMPERED
632                           CABBAGE, W/ COCONUT MILK
633                CABBAGE AND POTATO, W/ COCONUT MILK
634                                  CABBAGE, TEMPERED
635                 CABBAGE, TEMPERED, W/ COCONUT MILK
648  GOTUKOLA, FRESH OR WATER-COOKED MALLUM W/SCRAP...
649        GOTUKOLA, TEMPERED MALLUM W/SCRAPED COCONUT

In [85]:
leafy_name = leafy_foods['Food'].iloc[0]
leafy_name

'KENDA, LEAFY VEGETABLE & RICE'

In [86]:
risk, msg = explain_food_drug_interaction(warfarin_idx, leafy_name)
print(drug_clean.loc[warfarin_idx, "Name"], "+", leafy_name, "→", risk, "|", msg)

Genericart Warfarin 2mg Tablet + KENDA, LEAFY VEGETABLE & RICE → 2 | High Risk – Avoid this combination; consult a doctor or pharmacist. Leafy green foods rich in vitamin K can reduce the blood-thinning effect of anticoagulant medicines.

In [87]:
normal_food = food_subset['Food'].iloc[50]  # example index
risk, msg = explain_food_drug_interaction(warfarin_idx, normal_food)
print(normal_food, "→", risk, "|", msg)

PARATA → 0 | Safe – No major interaction identified. No specific nutrient-triggered interaction was detected.

In [88]:
andol_idx = drug_clean[drug_clean['Name'].str.contains("Andol", case=False)].index[0]
risk, msg = explain_food_drug_interaction(andol_idx, "BEER")

print("Drug:", drug_clean.loc[andol_idx, "Name"])
print("Food: BEER")
print("Risk:", risk)
print("Explanation:", msg)

Drug: Andol 0.5mg Tablet
Food: BEER
Risk: 2
Explanation: High Risk – Avoid this combination; consult a doctor or pharmacist. Alcohol can increase drowsiness and CNS side effects of this medicine.

In [89]:
augmentin_idx = drug_clean[drug_clean['Name'].str.contains("Augmentin", case=False)].index[0]

high_calcium_food = food_subset.sort_values(by="calcium", ascending=False)['Food'].iloc[0]
risk, msg = explain_food_drug_interaction(augmentin_idx, high_calcium_food)

print("Drug:", drug_clean.loc[augmentin_idx, "Name"])
print("Food:", high_calcium_food)
print("Risk:", risk)
print("Explanation:", msg)

Drug: Augmentin 625 Duo Tablet
Food: MILK POWDER, WHOLE (FULL FAT)
Risk: 1
Explanation: Moderate – Use with caution and follow advice. High calcium in this food can reduce absorption of this antibiotic.

In [90]:
# Find warfarin drug
warfarin_idx = warfarin_rows.index[0]  # you already found this earlier

# Find a leafy green food
leafy_name = food_subset[food_subset['is_leafy_green'] == 1]['Food'].iloc[0]

risk, msg = explain_food_drug_interaction(warfarin_idx, leafy_name)

print("Drug:", drug_clean.loc[warfarin_idx, "Name"])
print("Food:", leafy_name)
print("Risk:", risk)
print("Explanation:", msg)

Drug: Genericart Warfarin 2mg Tablet
Food: KENDA, LEAFY VEGETABLE & RICE
Risk: 2
Explanation: High Risk – Avoid this combination; consult a doctor or pharmacist. Leafy green foods rich in vitamin K can reduce the blood-thinning effect of anticoagulant medicines.